---
- name: "EAP {{ eap_source_version }} to {{ target_eap_version }} migration playbook"
  hosts: all
  vars:
    eap_source_version: 7.3.0
    target_eap_version: 7.4.0
    eap_install_workdir: /opt/jboss_eap/
    previous_eap_home: "{{ eap_install_workdir }}/jboss-eap-{{ (eap_source_version.split('.'))[0:2] | join('.') }}/"
    target_eap_home: "{{ eap_install_workdir }}/jboss-eap-{{ (target_eap_version.split('.'))[0:2] | join('.') }}/"
  vars_files:
    - vars/jdbc_driver.yml
    - vars/eap_system_info.yml
  collections:
    - redhat.eap
  pre_tasks:
    - name: "Ensures new EAP {{ target_eap_version }} is installed"
      ansible.builtin.include_role:
        name: eap_install
      vars:
        eap_version: "{{ target_eap_version }}"

  tasks:
    - name: "Perform migration from {{ previous_eap_home }} to {{ target_eap_home }}."
      ansible.builtin.include_role:
        name: eap_migration
      vars:
        eap_migration_environment_props: eap.environment.properties.j2
