---
- name: "Ensures EAP {{ eap_source_version }} is installed and configured"
  hosts: all
  vars:
    eap_source_version: 7.3.0
    eap_home: "/opt/jboss_eap/jboss-eap-{{ (eap_source_version.split('.'))[0:2] | join('.') }}/"
  vars_files:
    - vars/jdbc_driver.yml
    - vars/eap_system_info.yml
  collections:
    - redhat.eap
  tasks:
    - name: "Install EAP {{ eap_source_version }}"
      ansible.builtin.include_role:
        name: eap_install
      vars:
        eap_version: "{{ eap_source_version }}"
        omit_rhn_output: False

    - name: "Install Maria DB driver in {{ eap_home }}"
      ansible.builtin.include_role:
        name: eap_driver

    - name: "Ensures JBoss EAP {{ eap_source_version }} is running"
      ansible.builtin.include_role:
        name: eap_systemd
      vars:
        eap_systemd_enabled: True
        eap_version: "{{ eap_source_version }}"

    - ansible.builtin.set_fact:
        path_to_driver: "{{ eap_driver_module_dir }}/{{ eap_driver_jar_filename }}"

    - block:
      - name: "Checks if MariaDB driver is activated"
        ansible.builtin.include_role:
          name: eap_utils
          tasks_from: jboss_cli.yml
        vars:
          jboss_cli_query: "/subsystem=datasources/jdbc-driver={{ eap_driver_module_name }}:read-resource"
      rescue:

      - name: "Deploy MariaDB driver is activated"
        ansible.builtin.include_role:
          name: eap_utils
          tasks_from: jboss_cli.yml
        vars:
          jboss_cli_query: "{{ item }}"
        loop:
          - "'/subsystem=datasources/jdbc-driver={{ eap_driver_module_name }}:add(driver-name={{ eap_driver_name }}, driver-module-name={{ eap_driver_module_name }}, driver-class-name={{ eap_driver_classname }})'"
          - "'data-source add --jndi-name={{ mariadb_jndi_name }} --name={{ mariadb_ds_name }} --connection-url={{ mariadb_connection_url }} --driver-name={{ eap_driver_module_name }}'"
          - ":write-config()"
