---
- name: Verify
  hosts: instance
  vars:
    mariadb_ds: MariaDBPool
    eap_service_name: eap.service
    target_eap_version: 7.4.0
    target_eap_home: "{{ eap_install_workdir }}/jboss-eap-{{ (target_eap_version.split('.'))[0:2] | join('.') }}/"
  vars_files:
    - ../../vars/jdbc_driver.yml
    - ../../vars/eap_system_info.yml
  collections:
    - redhat.eap
  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: "Check that JBoss EAP service '{{ eap_service_name }}' is running."
      ansible.builtin.assert:
        that:
          - ansible_facts is defined
          - ansible_facts.services is defined
          - ansible_facts.services[eap_service_name] is defined
          - ansible_facts.services[eap_service_name]['state'] == 'running'
        quiet: True

    - name: "Deploy MariaDB driver is activated"
      ansible.builtin.include_role:
        name: eap_utils
        tasks_from: jboss_cli.yml
      vars:
        eap_home: "{{ target_eap_home }}"
        jboss_cli_query: "{{ item }}"
      loop:
        - "'/subsystem=datasources/jdbc-driver={{ eap_driver_module_name }}:read-resource'"
